# this defines the base environment to BUILD a11y testing binders
# across different development versions.
name: a11y
channels:
  - conda-forge
  - nodefaults
dependencies:
  - black
  - doit
  - git
  - jupyter_server
  - jupyter-packaging
  - jupyterlab_server
  - matplotlib-base
  - nbclassic
  - nodejs>=12,<15,!=13.*
  - numpy
  - pip
  - python>=3.7,<3.10
  - twine
  - vega_datasets
  - wheel
  - xeus-python
  - yarn<2
