name: ci

on:
  push:
    branches: ci
  pull_request:
    branches: ci

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out this Repo
        uses: actions/checkout@v2

      - name: Set Up Binder environment
        uses: conda-incubator/setup-miniconda@master
        with:
          environment-file: .binder/environment.yml
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Run Binder postBuild
        run: |
          set -eux
          bash .binder/postBuild

      - name: Generate Reports
        run: |
          set -eux
          doit report |& tee logs/99.report.log

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: accessibility logs ${{ github.run_number }}
          path: |
            logs
        if: always()

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: accessibility reports ${{ github.run_number }}
          path: |
            reports
        if: always()
