name: Build Gitpod Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Gitpod Docker image
    runs-on: ubuntu-latest
    environment: a11y-dev
    if: "github.repository_owner == 'jupyter' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]')"
    steps:
      - name: Clone repository âš¡
        uses: actions/checkout@v3

      - name: Lint Docker ğŸ”
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: ./testing/tools/Dockerfile

      - name: Get refs
        shell: bash
        run: |
          export raw_branch=${GITHUB_REF#refs/heads/}
          echo "::set-output name=branch::${raw_branch//\//-}"
          echo "::set-output name=date::$(date +'%Y%m%d')"
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        id: getrefs

      - name: Set up Docker Buildx ğŸ³
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub ğŸ”‘
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ğŸ› ï¸
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: "."
          file: "./testing/tools/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            quansight/jupyter-a11y:${{ steps.getrefs.outputs.date }}-${{ steps.getrefs.outputs.branch}}-${{ steps.getrefs.outputs.sha8 }}
            quansight/jupyter-a11y:latest

      - name: Image digest ğŸ“–
        # Return details of the image build: sha and shell
        run: echo ${{ steps.docker_build.outputs.digest }}
